### ISSUE TITLE
Square brackets in API

### ISSUE THREAD

**Issue by elnurgar** [mwang87/NP-Classifier#60]
Hello,

I am using NPClassifier to organize the natural products library of our laboratory. I access to the chemical classes by url API https://npclassifier.gnps2.org/classify?smiles=<smiles>

However I have a problem with accessing for molecules where there are square brackets in the SMILES. For exemple https://npclassifier.gnps2.org/classify?smiles=COc1ccc2c(c1O)-c1c(O)c(OC)cc3c1C(C2)[N+](C)(C)CC3

I tried to replace square brackets by %5B and %5D, but it doesn't work. 

Can you help please?

Thank you

**Comment by oolonek** [comment]
Hi @elnurgar 

You would need to fully encode the SMILES string.

For this you can use the `urllib.parse` Python library

```python
import requests
from urllib.parse import quote

# Function to get NPC classification
def get_npc_classification(smiles):
    # Encode the SMILES string
    encoded_smiles = quote(smiles)

    print(f"Fetching data for encode SMILES: {encoded_smiles}")

    url = f"https://npclassifier.gnps2.org/classify?smiles={encoded_smiles}"

    response = requests.get(url)

    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error fetching data for SMILES: {smiles} - Status Code: {response.status_code}")
        return None
```

Which in your case should return an encoded_smiles string `COc1ccc2c%28c1O%29-c1c%28O%29c%28OC%29cc3c1C%28C2%29%5BN%2B%5D%28C%29%28C%29CC3`

This now works https://npclassifier.gnps2.org/classify?smiles=COc1ccc2c%28c1O%29-c1c%28O%29c%28OC%29cc3c1C%28C2%29%5BN%2B%5D%28C%29%28C%29CC3

**Comment by elnurgar** [comment]
Hi Pierre-Marie,

Thank you for your reply. I will try it with our database.
