### ISSUE TITLE
Is the result of calling the website API（https://npclassifier.ucsd.edu/） the same as the result of this local server?

### ISSUE THREAD

**Issue by xiangyataboy** [mwang87/NP-Classifier#61]
Thank you for creating such a great tool for categorising NPs! Would a server built to classify according to the README content of this project classify more NPs than the number of NPs classified on the website? Is it better to use this local model for the ones you can't find on the website?

**Comment by mwang87** [comment]
NP Classifer will classify any smiles provided on demand.

**Comment by xiangyataboy** [comment]
Hello and thank you for your reply . Does it mean that any smiles can be categorised if the model is deployed locally, there are still uncategorised ones on the website?

> NP分类器将根据需要对任何微笑进行分类。

**Comment by xiangyataboy** [comment]
> NP Classifer will classify any smiles provided on demand.

Hello and thank you for your reply . Does it mean that any smiles can be categorised if the model is deployed locally, there are still uncategorised ones on the website?

**Comment by mwang87** [comment]
What do you mean by categorized?

**Comment by xiangyataboy** [comment]
> What do you mean by categorized?

Sorry, my expression may not be clear, categorised is Classified, the problem I encountered is that I use SMILES to query through the website (https://npclassifier.ucsd.edu/), but there are still some SMILES that can't be queried, if I follow https://github. com/mwang87/NP-Classifier this project is deployed locally, can I check it?

**Comment by mwang87** [comment]
I would recommend using the maintained version here:

https://npclassifier.gnps2.org/
